/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2017-10-18 07:19:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>Flex - Responsive HTML Template</title>\r\n");
      out.write("    \t<meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        \r\n");
      out.write("        <!--  헤더바 -->\r\n");
      out.write("\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/templatemo_misc.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/templatemo_style.css\">\r\n");
      out.write("\t\t<script src=\"js/vendor/modernizr-2.6.1-respond-1.1.0.min.js\"></script>\r\n");
      out.write("         \r\n");
      out.write("        <!--  헤더바 끝 -->\r\n");
      out.write("        <link href=\"graph/csslinegraph/csslinegraph.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        function goBoardPage() { location.href=\"views/board/boardView.jsp\"; }\r\n");
      out.write("        function goChatPage() { location.href=\"views/chatting/chat.html\"; }\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!--[if lt IE 7]>\r\n");
      out.write("            <p class=\"chromeframe\">You are using an outdated browser. <a href=\"http://browsehappy.com/\">Upgrade your browser today</a> or <a href=\"http://www.google.com/chromeframe/?redirect=true\">install Google Chrome Frame</a> to better experience this site.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 헤더 바  -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"main-header\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div id=\"menu-wrapper\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"logo-wrapper col-md-2 col-sm-2\">\r\n");
      out.write("                                    \r\n");
      out.write("                                </div> <!-- /.logo-wrapper -->\r\n");
      out.write("                                <div class=\"col-md-10 col-sm-10 main-menu text-right\">\r\n");
      out.write("                                    <div class=\"toggle-menu visible-sm visible-xs\"><i class=\"fa fa-bars\"></i></div>\r\n");
      out.write("                                    <ul class=\"menu-first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"/semi/tsearch\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"search\" name = \"keyword\" autocomplete>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"제목검색\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("                                        <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">카테고리</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:goBoardPage()\">공지사항</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">게시판</a></li>                                       \r\n");
      out.write("                                        <li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                            \r\n");
      out.write("                                    </ul>                                    \r\n");
      out.write("                                </div> <!-- /.main-menu -->\r\n");
      out.write("                            </div> <!-- /.row -->\r\n");
      out.write("                        </div> <!-- /#menu-wrapper -->                        \r\n");
      out.write("                    </div> <!-- /.container -->\r\n");
      out.write("                </div> <!-- /.main-header -->\r\n");
      out.write("            </div> <!-- /.site-header -->\r\n");
      out.write("<!-- 헤더 끝    -->\r\n");
      out.write("            <div class=\"site-slider\">\r\n");
      out.write("                <div class=\"slider\">\r\n");
      out.write("                    <div class=\"flexslider\">\r\n");
      out.write("                        <ul class=\"slides\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"overlay\"></div>\r\n");
      out.write("                                <img src=\"images/slide1.jpg\" alt=\"\">\r\n");
      out.write("                                <div class=\"slider-caption visible-md visible-lg\">\r\n");
      out.write("                                    <h2>다재다능 홈페이지에 오신걸 환영함니다</h2>\r\n");
      out.write("                                    <p>환영합니다</p>\r\n");
      out.write("<!--                                     <a href=\"#\" class=\"slider-btn\">Let us design!</a> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"overlay\"></div>\r\n");
      out.write("                                <img src=\"images/slide2.jpg\" alt=\"\">\r\n");
      out.write("                                <div class=\"slider-caption visible-md visible-lg\">\r\n");
      out.write("                                    <h2>우리 모두 누군가에게는 기쁨을줄 수 있는 하나의 재능을 가지고 있습니다</h2>\r\n");
      out.write("                                    <p>수익금은 전부 기부합니다.</p>\r\n");
      out.write("<!--                                     <a href=\"#\" class=\"slider-btn\">Go to Portfolio</a> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"overlay\"></div>\r\n");
      out.write("                                <img src=\"images/slide3.jpg\" alt=\"\">\r\n");
      out.write("                                <div class=\"slider-caption visible-md visible-lg\">\r\n");
      out.write("                                    <h2>이 홈페이지는 6명의 개발자로 만들어졌습니다</h2>\r\n");
      out.write("                                    <p>어서오세요</p>\r\n");
      out.write("<!--                                     <a href=\"#\" class=\"slider-btn\">Mobile Website</a> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div> <!-- /.flexslider -->\r\n");
      out.write("                </div> <!-- /.slider -->\r\n");
      out.write("            </div> <!-- /.site-slider -->\r\n");
      out.write("        </div> <!-- /.site-main -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("<!-- 카테고리 -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content-section\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"heading-section col-md-12 text-center\">\r\n");
      out.write("                        <h2>카테고리</h2>\r\n");
      out.write("                        <p>Our many talent classifications</p>\r\n");
      out.write("                    </div> <!-- /.heading-section -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p1.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>New Walk</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p1.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p2.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Boat</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p2.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p7.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Urban</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p7.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p8.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Cycling</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p8.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p3.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Digital Era</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p3.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p4.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Horizon</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p4.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p5.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Aquatic City</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p5.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p6.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>New Path</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p6.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("            </div> <!-- /.container -->\r\n");
      out.write("        </div> <!-- /#portfolio -->\r\n");
      out.write("<!-- 카테고리 끝-->\r\n");
      out.write("\r\n");
      out.write("<!-- 도움준사람들 -->\r\n");
      out.write("<div class=\"content-section\" id=\"our-team\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"heading-section col-md-12 text-center\">\r\n");
      out.write("                        <h2>많이 도움을 주신 전문가들</h2>\r\n");
      out.write("                        <p>Our people are very united for your success</p>\r\n");
      out.write("                    </div> <!-- /.heading-section -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"team-member col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"member-thumb\">\r\n");
      out.write("                            <img src=\"images/member1.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"team-overlay\">\r\n");
      out.write("                                <h3>Tracy</h3>\r\n");
      out.write("                                <span>Designer</span>\r\n");
      out.write("                                <ul class=\"social\">\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-linkedin\"></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div> <!-- /.team-overlay -->\r\n");
      out.write("                        </div> <!-- /.member-thumb -->\r\n");
      out.write("                    </div> <!-- /.team-member -->\r\n");
      out.write("                    <div class=\"team-member col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"member-thumb\">\r\n");
      out.write("                            <img src=\"images/member2.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"team-overlay\">\r\n");
      out.write("                                <h3>Cindy</h3>\r\n");
      out.write("                                <span>Developer</span>\r\n");
      out.write("                                <ul class=\"social\">\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-linkedin\"></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div> <!-- /.team-overlay -->\r\n");
      out.write("                        </div> <!-- /.member-thumb -->\r\n");
      out.write("                    </div> <!-- /.team-member -->\r\n");
      out.write("                    <div class=\"team-member col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"member-thumb\">\r\n");
      out.write("                            <img src=\"images/member3.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"team-overlay\">\r\n");
      out.write("                                <h3>Mary</h3>\r\n");
      out.write("                                <span>Director</span>\r\n");
      out.write("                                <ul class=\"social\">\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-linkedin\"></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div> <!-- /.team-overlay -->\r\n");
      out.write("                        </div> <!-- /.member-thumb -->\r\n");
      out.write("                    </div> <!-- /.team-member -->\r\n");
      out.write("                    <div class=\"team-member col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"member-thumb\">\r\n");
      out.write("                            <img src=\"images/member4.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"team-overlay\">\r\n");
      out.write("                                <h3>Linda</h3>\r\n");
      out.write("                                <span>Chief Executive</span>\r\n");
      out.write("                                <ul class=\"social\">\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-facebook\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-twitter\"></a></li>\r\n");
      out.write("                                    <li><a href=\"#\" class=\"fa fa-linkedin\"></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div> <!-- /.team-overlay -->\r\n");
      out.write("                        </div> <!-- /.member-thumb -->\r\n");
      out.write("                    </div> <!-- /.team-member -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 text-center\">\r\n");
      out.write("                        <div class=\"skills-heading\">\r\n");
      out.write("                            <h3 class=\"skills-title\">Design Skills</h3>\r\n");
      out.write("                            <p class=\"small-text\">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> <!-- /.col-md-12 -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-8 col-sm-6\">\r\n");
      out.write("                        <p>Aliquam faucibus in dolor sed vestibulum. Sed adipiscing malesuada luctus. Morbi tincidunt, tellus scelerisque scelerisque scelerisque, sapien dui pretium augue, at consectetur sapien tellus vitae nunc. Ut vitae metus quis nulla cursus adipiscing pretium vel dolor. Fusce lacinia accumsan arcu, quis porttitor nisi tincidunt ut. Nunc malesuada nunc eget nunc sollicitudin posuere. Maecenas vitae tortor quis odio hendrerit sagittis.<br><br>\r\n");
      out.write("\t\t\t\t\t\tEtiam tincidunt, magna eu elementum tristique, sapien nisl venenatis lacus, nec sagittis lectus dui eget lorem. Donec in tempus mi. Aenean egestas interdum dolor, et mollis lectus consequat. Mauris ullamcorper, felis sit amet gravida malesuada, nisi sem rhoncus massa, non tempor est erat sit amet diam.<!-- spacing for mobile viewing --><br><br>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("                    </div> <!-- /.col-md-8 -->\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("                        <ul class=\"progess-bars\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"90\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 90%;\">Photoshop 90%</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%;\">HTML CSS 80%</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"70\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 70%;\">Development 70%</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%;\">Marketing 80%</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div> <!-- /.col-md-4 -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("            </div> <!-- /.container -->\r\n");
      out.write("        </div> <!-- /#our-team -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--많이 도와준사람 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 최신/마감 -->\r\n");
      out.write("  <div class=\"content-section\" id=\"services\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"heading-section col-md-12 text-center\">\r\n");
      out.write("                        <h2>최신/마감</h2>\r\n");
      out.write("                        <p>We have many talents.</p>\r\n");
      out.write("                    </div> <!-- /.heading-section -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"service-item\" id=\"service-1\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-file-code-o\"></i>\r\n");
      out.write("                            </div> <!-- /.service-icon -->\r\n");
      out.write("                            <div class=\"service-content\">\r\n");
      out.write("                                <div class=\"inner-service\">\r\n");
      out.write("                                   <h3>HTML5 Coding</h3>\r\n");
      out.write("                                   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, assumenda, eveniet, consectetur, ex doloribus veniam asperiores incidunt mollitia placeat aniet.</p> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> <!-- /.service-content -->\r\n");
      out.write("                        </div> <!-- /#service-1 -->\r\n");
      out.write("                    </div> <!-- /.col-md-3 -->\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"service-item\" id=\"service-2\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-paper-plane-o\"></i>\r\n");
      out.write("                            </div> <!-- /.service-icon -->\r\n");
      out.write("                            <div class=\"service-content\">\r\n");
      out.write("                                <div class=\"inner-service\">\r\n");
      out.write("                                   <h3>Our Support</h3>\r\n");
      out.write("                                   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, assumenda, eveniet, consectetur, ex doloribus veniam asperiores incidunt mollitia placeat aniet.</p> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> <!-- /.service-content -->\r\n");
      out.write("                        </div> <!-- /#service-1 -->\r\n");
      out.write("                    </div> <!-- /.col-md-3 -->\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"service-item\" id=\"service-3\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-institution\"></i>\r\n");
      out.write("                            </div> <!-- /.service-icon -->\r\n");
      out.write("                            <div class=\"service-content\">\r\n");
      out.write("                                <div class=\"inner-service\">\r\n");
      out.write("                                   <h3>Our Design</h3>\r\n");
      out.write("                                   <p>We make HTML CSS templates that are responsive for any screen size on any device. Feel free to download and use our templates without restrictions.</p> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> <!-- /.service-content -->\r\n");
      out.write("                        </div> <!-- /#service-1 -->\r\n");
      out.write("                    </div> <!-- /.col-md-3 -->\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"service-item\" id=\"service-4\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-flask\"></i>\r\n");
      out.write("                            </div> <!-- /.service-icon -->\r\n");
      out.write("                            <div class=\"service-content\">\r\n");
      out.write("                                <div class=\"inner-service\">\r\n");
      out.write("                                   <h3>Go for mobile</h3>\r\n");
      out.write("                                   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, assumenda, eveniet, consectetur, ex doloribus veniam asperiores incidunt mollitia placeat aniet.</p> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> <!-- /.service-content -->\r\n");
      out.write("                        </div> <!-- /#service-1 -->\r\n");
      out.write("                    </div> <!-- /.col-md-3 -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("            </div> <!-- /.container -->\r\n");
      out.write("        </div> <!-- /#services -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 이색재능 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"content-section\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"heading-section col-md-12 text-center\">\r\n");
      out.write("                        <h2>이색 재능</h2>\r\n");
      out.write("                        <p>New Creative Talent</p>\r\n");
      out.write("                    </div> <!-- /.heading-section -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p1.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>New Walk</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p1.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p2.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Boat</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p2.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p7.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Urban</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p7.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                    <div class=\"portfolio-item col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-thumb\">\r\n");
      out.write("                            <img src=\"images/gallery/p8.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"portfolio-overlay\">\r\n");
      out.write("                                <h3>Cycling</h3>\r\n");
      out.write("                                <p>Asperiores commodi illo fuga perferendis dolore repellendus sapiente ipsum.</p>\r\n");
      out.write("                                <a href=\"images/gallery/p8.jpg\" data-rel=\"lightbox\" class=\"expand\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div> <!-- /.portfolio-overlay -->\r\n");
      out.write("                        </div> <!-- /.portfolio-thumb -->\r\n");
      out.write("                    </div> <!-- /.portfolio-item -->\r\n");
      out.write("                   \r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("            </div> <!-- /.container -->\r\n");
      out.write("        </div> <!-- /#portfolio -->\r\n");
      out.write("<!-- 이색재능 끝-->\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 기부 현황 -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("  \r\n");
      out.write("  <div style=\"float:left; margin-right:120px;\">\r\n");
      out.write("<h3>기부 현황</h3>\r\n");
      out.write("<p>(in year)</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<dl class=\"csslinegraph\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<dt>Day 1</dt>\r\n");
      out.write("\t\t<dd class=\"first\"><span class=\"pi0 i1\"><em>3</em></span></dd>\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 2</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi1 i10\"><em>36</em></span></dd>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 3</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd11 d d4\"><em>23</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 4</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi7 i10\"><em>56</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 5</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd17 d d0\"><em>55</em></span></dd>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 6</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd17 d d7\"><em>32</em></span></dd>\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 7</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi10 i14\"><em>79</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 8</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd24 d d2\"><em>74</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 9</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi22 i1\"><em>77</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 10</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi23 i2\"><em>83</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 11</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd25 d d15\"><em>34</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 12</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi10 i2\"><em>39</em></span></dd>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t</dl>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"float:left;\">\r\n");
      out.write("\r\n");
      out.write("    <h2>재능 별 기부 현황</h2>\r\n");
      out.write("\t<p>(in percentages)</p>        \r\n");
      out.write("    \r\n");
      out.write("\t<dl class=\"csslinegraph\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<dt>Day 1</dt>\r\n");
      out.write("\t\t<dd class=\"first\"><span class=\"pi12 i5\"><em>3</em></span></dd>\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 2</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi17 i10\"><em>36</em></span></dd>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 3</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd27 d d18\"><em>23</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 4</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi9 i15\"><em>56</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 5</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi24 i1\"><em>55</em></span></dd>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 6</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd25 d d13\"><em>32</em></span></dd>\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 7</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi12 i9\"><em>79</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 8</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi21 i8\"><em>74</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 9</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd29 d d22\"><em>77</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 10</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi7 i2\"><em>83</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 11</dt>\r\n");
      out.write("\t\t<dd><span class=\"pd9 d d4\"><em>34</em></span></dd>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  <dt>Day 12</dt>\r\n");
      out.write("\t\t<dd><span class=\"pi5 i14\"><em>39</em></span></dd>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t</dl>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div></div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write(" <!-- 기부 현황  -->\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("        <div id=\"footer\" style=\"clear:both;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-8 col-xs-12 text-left\">\r\n");
      out.write("                        <span>Copyright &copy; 2014 Company Name</span>\r\n");
      out.write("                  </div> <!-- /.text-center -->\r\n");
      out.write("                    <div class=\"col-md-4 hidden-xs text-right\">\r\n");
      out.write("                        <a href=\"#top\" id=\"go-top\">Back to top</a>\r\n");
      out.write("                    </div> <!-- /.text-center -->\r\n");
      out.write("                </div> <!-- /.row -->\r\n");
      out.write("            </div> <!-- /.container -->\r\n");
      out.write("        </div> <!-- /#footer -->\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"js/vendor/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("        <script>window.jQuery || document.write('<script src=\"js/vendor/jquery-1.11.0.min.js\"><\\/script>')</script>\r\n");
      out.write("        <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("        <script src=\"js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
