
DROP TABLE CATEGORY_BOARD CASCADE CONSTRAINTS;

CREATE TABLE CATEGORY_BOARD(
    CATEGORY_NO NUMBER CONSTRAINT PK_CATEGORY PRIMARY KEY,
    USER_ID VARCHAR2(15) NOT NULL,
    CATEGORY_GROUP NUMBER NOT NULL,
    CATEGORY_TITLE VARCHAR2(50) NOT NULL,
    CATEGORY_WRITER VARCHAR2(15) NOT NULL,
    CATEGORY_CONTENT VARCHAR2(2000) NOT NULL,
    CATEGORY_DATE DATE DEFAULT SYSDATE,
    CATEGORY_READCOUNT NUMBER DEFAULT 0,
    CATEGORY_DONATION NUMBER DEFAULT 0,
    WORK_DATE NUMBER DEFAULT 0,
    CATEGORY_LEVEL NUMBER,
    CATEGORY_REF NUMBER,
    CATEGORY_REPLY_REF NUMBER,
    CATEGORY_REPLY_SEQ NUMBER,
    PHONE CHAR(11),
    EMAIL VARCHAR2(30),
    ORIGINAL_IMAGE VARCHAR2(100),
    RENAME_IMAGE VARCHAR2(1000),
    SPECIAL CHAR(1) DEFAULT 'N',
    APPROVAL CHAR(1) DEFAULT 'N'
);



COMMENT ON COLUMN CATEGORY_BOARD.CATEGORY_NO IS '카테고리게시글번호';
COMMENT ON COLUMN CATEGORY_BOARD.USER_ID IS '아이디';
COMMENT ON COLUMN CATEGORY_BOARD.CATEGORY_GROUP IS '카테고리분류';
COMMENT ON COLUMN CATEGORY_BOARD.CATEGORY_TITLE IS '카테고리게시글이름';
COMMENT ON COLUMN CATEGORY_BOARD.CATEGORY_DATE IS '작성일자';
COMMENT ON COLUMN CATEGORY_BOARD.CATEGORY_DONATION IS '기부금';
COMMENT ON COLUMN CATEGORY_BOARD.WORK_DATE IS '작업일';
COMMENT ON COLUMN CATEGORY_BOARD.ORIGINAL_IMAGE IS '메인이미지';
COMMENT ON COLUMN CATEGORY_BOARD.ORIGINAL_IMAGE IS '이름바뀐이미지';
COMMENT ON COLUMN CATEGORY_BOARD.CATEGORY_CONTENT IS '상세내용';
COMMENT ON COLUMN CATEGORY_BOARD.PHONE IS '전화번호';
COMMENT ON COLUMN CATEGORY_BOARD.EMAIL IS '이메일';
COMMENT ON COLUMN CATEGORY_BOARD.CATEGORY_READCOUNT IS '조회수';




