DROP TABLE CHAT CASCADE CONSTRAINTS;

CREATE TABLE CHAT (
  CHAT_WRITER VARCHAR2(15) NOT NULL,
  CHAT_RECIVER VARCHAR2(15) NOT NULL,
  CHAT_DATE DATE DEFAULT SYSDATE,
  CHAT_CONTENT LONG,
  CHAT_ORIGINAL_FILENAME VARCHAR2(100),
  CHAT_RENAME_FILENAME VARCHAR2(100),  
  CONSTRAINT FK_CHATWR FOREIGN KEY (CHAT_WRITER) REFERENCES MEMBER (MEMBER_ID),
  CONSTRAINT FK_CHATRE FOREIGN KEY (CHAT_RECIVER) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON COLUMN CHAT.CHAT_WRITER IS '채팅 발신자';
COMMENT ON COLUMN CHAT.CHAT_RECIVER IS '채팅 수신자';
COMMENT ON COLUMN CHAT.CHAT_DATE IS '채팅 전송날짜';
COMMENT ON COLUMN CHAT.CHAT_CONTENT IS '채팅 내용';
COMMENT ON COLUMN CHAT.CHAT_ORIGINAL_FILENAME IS '채팅 원래 첨부파일명';
COMMENT ON COLUMN CHAT.CHAT_RENAME_FILENAME IS '채팅 바뀐 첨부파일명';

--------------------- 샘플 데이터 -------------------------------

COMMIT;